### ISSUE TITLE
docker images

### ISSUE THREAD

**Issue by pbranly** [journaldethomas/home-assistant-config#1]
bonjour,
Superbes cards.
ou avez vous trouvé l'ensemble des icones pour les dockers ?
Merci d'avance
Cdlt
Philippe

**Comment by journaldethomas** [comment]
Bonjour,
Désolé je n'avais pas vu cette issue... je n'ai pas encore trop l'habitude de GitHub :)
J'ai fait moi même les icônes en téléchargeant les logo des différentes applications. Vous pouvez toujours télécharger sur ce GitHub les icônes si elles correspondent à vos applications...
Thomas.
